# C - Category
- name: 'C-bug'
  description: 'Category: bug'
  color: '8ec1f5'
- name: 'C-security'
  description: 'Category: security'
  color: '8ec1f5'
- name: 'C-enhancement'
  description: 'Category: enhancement'
  color: '8ec1f5'
- name: 'C-cleanup'
  description: 'Category: cleanup within codebase'
  color: '8ec1f5'
- name: 'C-GitHub Actions'
  description: 'Category: GitHub Actions'
  color: '8ec1f5'
- name: 'C-improvement'
  description: 'Category: improvement'
  color: '8ec1f5'
- name: 'C-development'
  description: 'Category: development'
  color: '8ec1f5'

# P - Priority
- name: 'P-high'
  description: 'Priority: High'
  color: 'f79d6d'

- name: 'Help wanted'
  color: 'ab7aeb'
- name: 'good first issue'
  color: 'ab7aeb'
