[package]
name = "babyrite"
version = "0.1.0"
edition = "2021"
license = "MIT"
repository = "https://github.com/m1sk9/babyrite"

[features]
enable_sentry = []

[dependencies]
anyhow = { version = "1.0" }
dotenvy = { version = "0.15" }
once_cell = { version = "1.18" }
sentry = { version = "0.31" }
tracing = { version = "0.1" }
tracing-subscriber = { version = "0.3" }

[dependencies.serenity]
version = "0.11"
features = ["client", "gateway", "model", "cache", "rustls_backend"]
default-features = false

[dependencies.tokio]
version = "1.32"
features = ["macros", "rt-multi-thread", "time"]
