services:
  app:
    image: ghcr.io/m1sk9/babyrite:v0
    env_file:
      - .env
    volumes:
      - ./config/config.yaml:/config/config.yaml
    environment:
      - RUST_LOG=babyrite=info
    restart: always
