name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  check:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout branch
        uses: actions/checkout@v6

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          components: clippy, rustfmt

      - name: Setup cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          prefix-key: "babyrite/gh-actions-cache"

      - name: Run rustfmt
        run: cargo fmt --all -- --check

      - name: Run clippy
        run: cargo clippy --all-targets --all-features

      - name: Run test
        run: cargo test --verbose

  coverage:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Setup cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          prefix-key: "babyrite/gh-actions-cache"

      - name: Install cargo-llvm-cov
        uses: taiki-e/install-action@a57ddfbcd928cf9406a78dcc300dacc5d367a547 # v2
        with:
          tool: cargo-llvm-cov

      - name: Generate code coverage
        run: cargo llvm-cov --all-features --workspace --codecov --output-path codecov.json

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@671740ac38dd9b0130fbe1cec585b89eea48d3de # v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: codecov.json
          fail_ci_if_error: true

  build:
    name: build (${{ matrix.job.target }})
    runs-on: ${{ matrix.job.os || 'ubuntu-24.04' }}
    needs: check
    strategy:
      fail-fast: false
      matrix:
        job:
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            use-cross: false
          - os: ubuntu-24.04
            target: x86_64-unknown-linux-musl
            use-cross: true
          - os: macos-15-intel
            target: x86_64-apple-darwin
            use-cross: false
          - os: macos-15
            target: aarch64-apple-darwin
            use-cross: false
          - os: windows-2025
            target: x86_64-pc-windows-msvc
            use-cross: false
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Setup toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
          target: ${{ matrix.job.target }}

      - name: Setup cache
        uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
        with:
          prefix-key: "babyrite/gh-actions-cache"

      - name: Install cross
        if: matrix.job.use-cross
        run: cargo install cross

      # note: In Ubuntu-latest (Ubuntu 24), musl-tools has disappeared, so it must be installed separately.
      - name: Install musl-gcc
        if: matrix.job.target == 'x86_64-unknown-linux-musl'
        run: sudo apt-get update && sudo apt-get install -y musl-tools

      - name: Build
        run: |
          cargo build --verbose --target ${{ matrix.job.target }}
