name: rustfmt

on:
  push:
    branches:
      - main
      - 'release/v*.*.*'
  pull_request:
    branches:
      - main
      - 'release/v*.*.*'

jobs:
  fmt:
    runs-on: ubuntu-latest
    name: rustfmt babyrite
    steps:
      - name: Checkout branch
        uses: actions/checkout@v4

      - name: Setup toolchain
        uses: mkroening/rust-toolchain-toml@v1.2.0

      - name: Setup cache
        uses: Swatinem/rust-cache@v2
        with:
          prefix-key: "babyrite/gh-actions-cache"

      - name: Run rustfmt
        run: cargo fmt --all -- --check
